This is the result of the test:

$ ./manage.py test my_app
Django version: (1, 7, 4, 'final', 0)
Creating test database for alias 'default'...
F..
======================================================================
FAIL: test_django_sum (my_app.tests.SumTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mark/projects/django-sum-bug.git/my_project/my_app/tests.py", line 55, in test_django_sum
    self.assertEqual(rows.aggregate(Sum('amount'))['amount__sum'], 30)
AssertionError: Decimal('40.00') != 30

----------------------------------------------------------------------
Ran 3 tests in 0.019s

FAILED (failures=1)
Destroying test database for alias 'default'...
